import "@/styles/globals.css"
import { Link } from "@nextui-org/react"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import NextLink from "next/link"
import Script from "next/script"
import { Providers } from "./providers"

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html
            lang="en"
            className={`dark ${GeistSans.variable} ${GeistMono.variable}`}
        >
            <body>
                <Providers className="h-screen">
                    <header className="absolute top-0 text-center w-full text-6xl font-bold font-mono p-4">
                        <NextLink
                            // as={NextLink}
                            href="/"
                            // isBlock={true}
                            className="hover:opacity-75 transition-all"
                        >
                            Safe in the Air?
                        </NextLink>
                    </header>

                    <main className="flex min-h-screen flex-col items-center justify-center text-white">
                        {children}
                    </main>
                    <footer className="absolute bottom-0 w-full text-lg p-4">
                        Made by{" "}
                        <Link
                            as={NextLink}
                            href="https://shreyans.sh"
                            isExternal={true}
                            className="text-inherit underline underline-offset-2 text-lg"
                        >
                            Shreyans Jain
                        </Link>
                        ; Inspired by{" "}
                        <Link
                            as={NextLink}
                            href="https://en.wikipedia.org/wiki/Boredom"
                            isExternal={true}
                            className="text-inherit underline underline-offset-2 text-lg"
                        >
                            Boredom
                        </Link>
                        .
                    </footer>
                </Providers>
                <Script
                    async={true}
                    data-website-id="958ed8b1-6d14-4a94-848a-e75533b55f43"
                    src="https://umami.shreyans.sh/script.js"
                />
            </body>
        </html>
    )
}
